---
- hosts: all
  remote_user: "ec2-user"
  gather_facts: true
  vars:
    ansible_ssh_private_key_file: "~/.ssh/ssh-aws"
  tasks:
    - name: ensure nginx is at the latest version
      yum: name=nginx state=latest
    - name: start nginx
      service:
          name: nginx
          state: started