---
- hosts: all
  remote_user: "ubuntu"
  gather_facts: false
  become: yes
  vars:
    ansible_ssh_private_key_file: "~/.ssh/SSHKeys.pem"
  tasks:
    - ping
      # ping
      # apt: name=nginx state=latest
    # - name: start nginx
    #   service:
    #       name: nginx
    #       state: started